/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#62df7d",
        "secondary-container": "#7cf994",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#006e2d",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002109",
        "inverse-primary": "#4ae176",
        "on-tertiary-fixed-variant": "#783200",
        "on-tertiary-container": "#6d2d00",
        "surface-container": "#e5eeff",
        "on-surface-variant": "#3d4a3d",
        "primary-fixed": "#6bff8f",
        "background": "#f8f9ff",
        "primary": "#006e2f",
        "outline-variant": "#bccbb9",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002109",
        "surface-tint": "#006e2f",
        "surface-variant": "#d3e4fe",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb690",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#7ffc97",
        "on-secondary-container": "#007230",
        "tertiary": "#9d4300",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#004b1e",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "tertiary-container": "#ff8e4d",
        "primary-fixed-dim": "#4ae176",
        "on-secondary-fixed-variant": "#005320",
        "primary-container": "#22c55e",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "outline": "#6d7b6c",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "on-tertiary-fixed": "#341100",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#005321"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "80px",
        "md": "24px",
        "sm": "16px",
        "margin-desktop": "120px",
        "lg": "48px",
        "xs": "8px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}